var profile = {
	basePath: '../src/',
	action: 'release',
	cssOptimize: 'comments',
	mini: true,
	optimize: 'closure',
	layerOptimize: 'closure',
	packages: [
		{ name: "esri-init", location: "esri-init" },
		{ name: 'app', location: 'app' },
		{ name: 'dgrid', location: 'dgrid'},
		{ name: 'dijit', location: "dijit"},
		{ name: 'dojo', location: "dojo"},
		{ name: 'dojox', location: "dojox"},
		{ name: 'put-selector', location: 'put-selector' },
		{ name: 'xstyle', location: 'xstyle' },
		{ name: 'esri', location: 'esri' }
	],
	stripConsole: 'all',
	selectorEngine: 'lite',
	layers: {
		'dojo/dojo': {
			boot: true,
			customBase: true
		},
		'app/main': {
			include: [
				// If the compiler missed some of the includes they can be manually added here
				"dojo/nls/dojo_en-us",
				"dojox/gfx/path",
				"dojox/gfx/shape",
				"dojox/gfx/svg",
				"esri/dijit/Attribution"
			],
			exclude: [
				"dijit/a11y",
				"dijit/a11yclick",
				"dijit/BackgroundIframe",
				"dijit/Destroyable",
				"dijit/Dialog",
				"dijit/DialogUnderlay",
				"dijit/focus",
				"dijit/form/Button",
				"dijit/form/ComboButton",
				"dijit/form/DropDownButton",
				"dijit/form/TextBox",
				"dijit/form/ToggleButton",
				"dijit/form/ValidationTextBox",
				"dijit/form/_ButtonMixin",
				"dijit/form/_FormMixin",
				"dijit/form/_FormValueMixin",
				"dijit/form/_FormValueWidget",
				"dijit/form/_FormWidget",
				"dijit/form/_FormWidgetMixin",
				"dijit/form/_TextBoxMixin",
				"dijit/form/_ToggleButtonMixin",
				"dijit/hccss",
				"dijit/layout/ContentPane",
				"dijit/layout/utils",
				"dijit/layout/_ContentPaneResizeMixin",
				"dijit/main",
				"dijit/place",
				"dijit/popup",
				"dijit/registry",
				"dijit/selection",
				"dijit/Tooltip",
				"dijit/TooltipDialog",
				"dijit/typematic",
				"dijit/Viewport",
				"dijit/WidgetSet",
				"dijit/_AttachMixin",
				"dijit/_base",
				"dijit/_base/focus",
				"dijit/_base/manager",
				"dijit/_base/place",
				"dijit/_base/popup",
				"dijit/_base/scroll",
				"dijit/_base/sniff",
				"dijit/_base/typematic",
				"dijit/_base/wai",
				"dijit/_base/window",
				"dijit/_Container",
				"dijit/_CssStateMixin",
				"dijit/_DialogMixin",
				"dijit/_FocusMixin",
				"dijit/_HasDropDown",
				"dijit/_OnDijitClickMixin",
				"dijit/_Templated",
				"dijit/_TemplatedMixin",
				"dijit/_Widget",
				"dijit/_WidgetBase",
				"dijit/_WidgetsInTemplateMixin",
				"dojo/aspect",
				"dojo/cache",
				"dojo/cldr/supplemental",
				"dojo/cookie",
				"dojo/date",
				"dojo/date/locale",
				"dojo/date/stamp",
				"dojo/Deferred",
				"dojo/DeferredList",
				"dojo/dnd/autoscroll",
				"dojo/dnd/common",
				"dojo/dnd/Moveable",
				"dojo/dnd/Mover",
				"dojo/dnd/TimedMoveable",
				"dojo/dom",
				"dojo/dom-attr",
				"dojo/dom-class",
				"dojo/dom-construct",
				"dojo/dom-form",
				"dojo/dom-geometry",
				"dojo/dom-prop",
				"dojo/dom-style",
				"dojo/domReady",
				"dojo/errors/CancelError",
				"dojo/errors/create",
				"dojo/errors/RequestError",
				"dojo/errors/RequestTimeoutError",
				"dojo/Evented",
				"dojo/fx",
				"dojo/fx/Toggler",
				"dojo/has",
				"dojo/hccss",
				"dojo/html",
				"dojo/i18n",
				"dojo/io-query",
				"dojo/io/iframe",
				"dojo/io/script",
				"dojo/json",
				"dojo/keys",
				"dojo/loadInit",
				"dojo/main",
				"dojo/mouse",
				"dojo/NodeList-dom",
				"dojo/number",
				"dojo/on",
				"dojo/parser",
				"dojo/promise/all",
				"dojo/promise/instrumentation",
				"dojo/promise/Promise",
				"dojo/promise/tracer",
				"dojo/query",
				"dojo/ready",
				"dojo/regexp",
				"dojo/request",
				"dojo/request/default",
				"dojo/request/handlers",
				"dojo/request/iframe",
				"dojo/request/script",
				"dojo/request/util",
				"dojo/request/watch",
				"dojo/request/xhr",
				"dojo/require",
				"dojo/selector/acme",
				"dojo/selector/_loader",
				"dojo/sniff",
				"dojo/Stateful",
				"dojo/string",
				"dojo/text",
				"dojo/topic",
				"dojo/touch",
				"dojo/uacss",
				"dojo/when",
				"dojo/window",
				"dojo/_base/array",
				"dojo/_base/browser",
				"dojo/_base/Color",
				"dojo/_base/config",
				"dojo/_base/connect",
				"dojo/_base/declare",
				"dojo/_base/Deferred",
				"dojo/_base/event",
				"dojo/_base/fx",
				"dojo/_base/html",
				"dojo/_base/json",
				"dojo/_base/kernel",
				"dojo/_base/lang",
				"dojo/_base/loader",
				"dojo/_base/NodeList",
				"dojo/_base/sniff",
				"dojo/_base/unload",
				"dojo/_base/url",
				"dojo/_base/window",
				"dojo/_base/xhr",
				"dojox/collections/ArrayList",
				"dojox/collections/_base",
				"dojox/gfx",
				"dojox/gfx/matrix",
				"dojox/gfx/renderer",
				"dojox/gfx/_base",
				"dojox/xml/parser",
				"esri/arcgis/OAuthInfo",
				"esri/arcgis/utils",
				"esri/basemaps",
				"esri/Color",
				"esri/config",
				"esri/Credential",
				"esri/deferredUtils",
				"esri/dijit/Attribution",
				"esri/dijit/Popup",
				"esri/dijit/PopupRenderer",
				"esri/dijit/PopupTemplate",
				"esri/dijit/_EventedWidget",
				"esri/domUtils",
				"esri/Evented",
				"esri/fx",
				"esri/geometry",
				"esri/geometry/Extent",
				"esri/geometry/geodesicUtils",
				"esri/geometry/Geometry",
				"esri/geometry/jsonUtils",
				"esri/geometry/mathUtils",
				"esri/geometry/Multipoint",
				"esri/geometry/normalizeUtils",
				"esri/geometry/Point",
				"esri/geometry/Polygon",
				"esri/geometry/Polyline",
				"esri/geometry/Rect",
				"esri/geometry/scaleUtils",
				"esri/geometry/ScreenPoint",
				"esri/geometry/screenUtils",
				"esri/geometry/webMercatorUtils",
				"esri/graphic",
				"esri/graphicsUtils",
				"esri/IdentityManager",
				"esri/IdentityManagerBase",
				"esri/IdentityManagerDialog",
				"esri/InfoTemplate",
				"esri/InfoWindowBase",
				"esri/kernel",
				"esri/lang",
				"esri/layers/agscommon",
				"esri/layers/agsdynamic",
				"esri/layers/agstiled",
				"esri/layers/ArcGISDynamicMapServiceLayer",
				"esri/layers/ArcGISMapServiceLayer",
				"esri/layers/ArcGISTiledMapServiceLayer",
				"esri/layers/CodedValueDomain",
				"esri/layers/DataSource",
				"esri/layers/Domain",
				"esri/layers/DynamicLayerInfo",
				"esri/layers/DynamicMapServiceLayer",
				"esri/layers/FeatureEditResult",
				"esri/layers/FeatureLayer",
				"esri/layers/FeatureTemplate",
				"esri/layers/FeatureType",
				"esri/layers/Field",
				"esri/layers/graphics",
				"esri/layers/GraphicsLayer",
				"esri/layers/GridLayout",
				"esri/layers/HeatmapManager",
				"esri/layers/ImageParameters",
				"esri/layers/InheritedDomain",
				"esri/layers/JoinDataSource",
				"esri/layers/LabelClass",
				"esri/layers/layer",
				"esri/layers/LayerDataSource",
				"esri/layers/LayerDrawingOptions",
				"esri/layers/LayerInfo",
				"esri/layers/LayerMapSource",
				"esri/layers/LayerSource",
				"esri/layers/LayerTimeOptions",
				"esri/layers/LOD",
				"esri/layers/MapImage",
				"esri/layers/MapImageLayer",
				"esri/layers/OnDemandMode",
				"esri/layers/OpenStreetMapLayer",
				"esri/layers/QueryDataSource",
				"esri/layers/RangeDomain",
				"esri/layers/RasterDataSource",
				"esri/layers/RenderMode",
				"esri/layers/SelectionMode",
				"esri/layers/SnapshotMode",
				"esri/layers/StreamMode",
				"esri/layers/TableDataSource",
				"esri/layers/TiledMapServiceLayer",
				"esri/layers/TileInfo",
				"esri/layers/TileMap",
				"esri/layers/TimeInfo",
				"esri/layers/TimeReference",
				"esri/layers/TrackManager",
				"esri/layerUtils",
				"esri/main",
				"esri/map",
				"esri/MapNavigationManager",
				"esri/MouseEvents",
				"esri/OAuthCredential",
				"esri/OAuthSignInHandler",
				"esri/plugins/popupManager",
				"esri/PluginTarget",
				"esri/PointerEvents",
				"esri/PopupBase",
				"esri/PopupInfo",
				"esri/PopupManager",
				"esri/renderer",
				"esri/renderers/ClassBreaksRenderer",
				"esri/renderers/DotDensityRenderer",
				"esri/renderers/HeatmapRenderer",
				"esri/renderers/jsonUtils",
				"esri/renderers/Renderer",
				"esri/renderers/ScaleDependentRenderer",
				"esri/renderers/SimpleRenderer",
				"esri/renderers/SymbolAger",
				"esri/renderers/TemporalRenderer",
				"esri/renderers/TimeClassBreaksAger",
				"esri/renderers/TimeRampAger",
				"esri/renderers/UniqueValueRenderer",
				"esri/request",
				"esri/ServerInfo",
				"esri/sniff",
				"esri/SpatialReference",
				"esri/symbol",
				"esri/symbols/CartographicLineSymbol",
				"esri/symbols/FillSymbol",
				"esri/symbols/Font",
				"esri/symbols/jsonUtils",
				"esri/symbols/LineSymbol",
				"esri/symbols/MarkerSymbol",
				"esri/symbols/PictureFillSymbol",
				"esri/symbols/PictureMarkerSymbol",
				"esri/symbols/ShieldLabelSymbol",
				"esri/symbols/SimpleFillSymbol",
				"esri/symbols/SimpleLineSymbol",
				"esri/symbols/SimpleMarkerSymbol",
				"esri/symbols/Symbol",
				"esri/symbols/TextSymbol",
				"esri/tasks/FeatureSet",
				"esri/tasks/GeometryService",
				"esri/tasks/query",
				"esri/tasks/QueryTask",
				"esri/tasks/RelationshipQuery",
				"esri/tasks/SpatialRelationship",
				"esri/tasks/StatisticDefinition",
				"esri/tasks/Task",
				"esri/tileUtils",
				"esri/TimeExtent",
				"esri/TouchEvents",
				"esri/units",
				"esri/urlUtils",
				"esri/utils",
				"esri/WKIDUnitConversion",
				"esri/_coremap",
				"esri/_time"
			]
		}
	},
	staticHasFeatures: {
		'dojo-trace-api': false,
		'dojo-log-api': false,
		'dojo-publish-privates': false,
		'dojo-sync-loader': false,
		'dojo-xhr-factory': false,
		'dojo-test-sniff': false
	},
	useSourceMaps : false
};